name: PublicKingdom
version: 0.1
main: net.zwet.publickingdom.PublicKingdom
authors: [JanSneeuw]
description: Kingdom plugin.
depend: [WorldGuard]
api-version: '1.13'
commands:
  K:
    description: Basecommand

